config/routes.rb
Rails.application.routes.draw do
  get 'view/registration'
  devise_for :users
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'

  resources :events do
    resources :registrations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations
  has_many(
    :organizers, -> { where('registrations.is_organizer = true') },
    through: :registrations, source: :user
  )
  has_many(
    :attendees, -> { where('registrations.canceled = false') },
    through: :registrations, source: :user
  )
  has_many(
    :cancels, -> { where('registrations.canceled = true') },
    through: :registrations, source: :user
  )
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class NotOrganizer < ActionController::ActionControllerError
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include AuthenticationHelper

  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user, only: %i[new edit update destroy create]
  before_action :authenticate_organizer!, only: %i[edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    ActiveRecord::Base.transaction do
      @event.save!

      # 作成者を organizer にする
      organizer = Registration.new(
        event_id: @event.id,
        user_id: current_user.id,
        is_organizer: true
      )
      organizer.save!
    end

    respond_to do |format|
      format.html { redirect_to @event, notice: 'Event was successfully created.' }
      format.json { render :show, status: :created, location: @event }
    end
# TODO
#  rescue => e
#    respond_to do |format|
#      format.html { render :new }
#      format.json { render json: @event.errors, status: :unprocessable_entity }
#    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :start, :end, :location, :main_content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  include AuthenticationHelper

  before_action :set_event, only: %i[new create]
  before_action :authenticate_user, only: %i[new create]

  def new
    @registration = Registration.new
  end

  def create
    @registration = @event.registrations.create(registration_params)
    # non-organizer cannot set is_organizer flag
    authenticate_organizer! if @registration.is_organizer
    @registration.save!

    respond_to do |format|
      format.html {
        redirect_to(
          @event,
          notice: 'Finished registration to this event successfully.'
        )
      }
      format.json {
        render :show, status: :created, location: @registration
      }
    end

    # TODO: error handling
  end

  def registration_params
    params.permit(:canceled, :is_organizer).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
# Provides authentication functions for controller classes
module AuthenticationHelper
  def authenticate_user
    unless user_signed_in?
      session[:previous_url] = request.fullpath
      redirect_to new_user_session_path, notice: 'サインインが必要です'
    end
  end

  def authenticate_organizer!
    raise NotOrganizer('このイベントの編集権がありません') unless
      @event.organizers.include?(current_user)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def render_md(md_text)
    renderer = CustomRender.new(render_options = {})
    markdown = Redcarpet::Markdown.new(renderer, autolink: true)

    raw(markdown.render(md_text))
  end

  class CustomRender < Redcarpet::Render::XHTML
    def header(text, level)
      level += 1 
      %(<h#{level} class="ui header">#{text}</h#{level}>)
    end
  end

  DAYS_OF_WEEK = %w[日 月 火 水 木 金 土]
  def format_date(datetime)
    # TODO: ユーザ設定から読み込み
    #d = datetime.in_time_zone('Asia/Tokyo')
    d = datetime
    wday = DAYS_OF_WEEK[d.wday]
    d.strftime("%Y/%m/%d (#{wday}) %H:%M %Z")
  end

  def organizers(event)
    r = event.attendees.where('attendees.is_organizer = true')
    r.map do |a|
      a.user
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :main_content %>
    <%= form.text_area :main_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1 class="ui header">イベント一覧</h1>

<% @events.each do |event| %>
<h3 class="ui top attached header"><%= link_to event.title, event %></h3>
<div class="ui attached segment">
  <div class="ui relaxed divided list">
    <div class="item">
      <span class="header">日時</span>
      <div class="description">
        <%= format_date(event.start) %>〜<%= format_date(event.end) %>
      </div>
    </div>
    <div class="item">
      <span class="header">会場</span>
      <div class="description"><%= event.location %></div>
    </div>
    <div class="item">
      <span class="header">主催者</span>
      <div class="description">&nbsp;</div>
    </div>
    <div>
      
    </div>
  </div>
</div>
<% end %>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="ui grid">
  <div class="twelve wide column">
    <h1 class="header"><%= @event.title %></h1>
  </div>
  <div class="right floated four wide column right aligned">
    
    <% if @event.attendees.include?(current_user) %>
      <%= link_to '申し込み済み', '#', class: 'ui button primary' %>
    <% else %>
      <%= link_to '参加する', new_event_registration_path(event_id: @event.id), class: 'ui button primary' %>
    <% end %>
  </div>
</div>

<div class="ui segment">
  <div class="ui relaxed divided list">
    <div class="item">
      <span class="header">日時</span>
      <div class="description">
        <%= format_date(@event.start) %>〜<%= format_date(@event.end) %>
      </div>
    </div>
    <div class="item">
      <span class="header">会場</span>
      <div class="description"><%= @event.location %></div>
    </div>
    <div class="item">
      <span class="header">主催者</span>
      <div class="description">
        <% @event.organizers.each do |u| %>
          <a class="ui image label"><i class="user icon"></i><%= u.email %></a>
        <% end %>
      </div>
    </div>
    <div class="item">
      <span class="header">参加者数</span>
      <div class="description">
        <%= @event.attendees.count %> 人 / <%= 10 %> 人
      </div>
    </div>
  </div>
</div>

<div class="ui horizontal divider">
  <i class="tag icon"></i>
  詳細
</div>

<div class="ui" id="event_main_content">
<%= render_md(@event.main_content) %>
</div>

<div id="attendees">
  <h2 class="ui center aligned icon header small">
    <i class="circular users icon"></i>
    参加者
  </h2>
  <ul>
    <% @event.attendees.each do |u| %>
      <li><a class="ui image label"><i class="user icon"></i><%= u.email %></a></li>
    <% end %>
  </ul>

  <h3 class="ui sub header">キャンセル</h3>
  <% if @event.cancels.count == 0 %>
    キャンセルしたユーザーはいません
  <% else %>
    <ul>
      <% @event.cancels.each do |u| %>
      <li><a class="ui image label"><i class="user icon"></i><%= u.email %></a></li>
      <% end %>
    </ul>
  <% end %>
</div>



<% if @event.organizers.include?(current_user) %>
<div class="ui segment">
<%= link_to 'Edit', edit_event_path(@event) %>
</div>  
<% end %>

<p>debug: <%= notice %></p>
<p><%= flash.keys() %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Radish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui fixed menu">
      <a href="/" class="header item">Radish</a>
      <div class="right menu">
        <% if user_signed_in? %>
        <div class="ui simple dropdown item">
          <%= current_user.email %>
          <i class="icon dropdown"></i>
          <div class="menu transition">
            <div class="item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            </div>
          </div>
        </div>
        <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: 'item' %>
        <% end %>
      </div>
    </div>
    <!-- BEGIEN Main -->
    <div class="ui main text container">
      <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <p id="notice" class="ui message info"><%= value %></p>
        <% elsif key == "alert" %>
        <p id="notice" class="ui message error"><%= value %></p>
        <% else %>
        <p id="notice" class="ui message"><%= key %>: <%= value %></p>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <!-- END Main -->
    <div class="ui inverted vertical footer segment">
    </div>
  </body>
</html>